const lista_unidades_solicitacoes = `
<option value="">Todas as unidades</option>
<option value="17">CENTRO DE ESPECIALIDADES ODONTOLOGICAS</option>
<option value="18">CENTRO ESTADUAL DE ATENCAO ESPEC DR SILVIO AMERICANO MENDES</option>
<option value="206">CENTRO MUNICIPAL DE ATENDIMENTO MULTIDICIPLINAR</option>
<option value="11">CLINICA MUNICIPAL DE FISIOTERAPIA JOAO HEIDER BATISTA DA SIL</option>
<option value="61">CONSULTAS PARTICULARES</option>
<option value="74">EMULTI B - UAPS VEREADOR MANOEL DOS SANTOS SILVA</option>
<option value="79">NASF C - UAPS DONA NININHA</option>
<option value="16">POLICLINICA MUNICIPAL DR SILVIO A MENDES</option>
<option value="68">POLICLINICA MUNICIPAL VIVA VIDA</option>
<option value="9">UAPS AGEU ALMEIDA</option>
<option value="3">UAPS ANTONINO DE ALMEIDA</option>
<option value="33">UAPS COMUNIDADES RURAIS</option>
<option value="4">UAPS DONA NININHA - HARMONIA</option>
<option value="78">UAPS DONA NININHA - UNIAO</option>
<option value="2">UAPS ED. FIS. DOUGLAS FREDERICO MIRANDA BATISTA</option>
<option value="75">UAPS ENFERMARIA MARY TATIANE ANTONIO LOPES - MAIS SAUDE</option>
<option value="8">UAPS ENFERMEIRA MARY TATIANE ANTUNES LOPES - ACOLHER</option>
<option value="77">UAPS JOAO DE DEUS SIMOES - EMAD 2</option>
<option value="76">UAPS JOAO DE DEUS SIMOES - EMAP</option>
<option value="13">UAPS JOAO DE DEUS SIMOES - VIDA</option>
<option value="34">UAPS LAGOA GRANDE LAGOA DOURADA</option>
<option value="7">UAPS MILTON MENDES DA SILVA</option>
<option value="56">UAPS VEREADOR JOSE SENA - CAMINHO</option>
<option value="6">UAPS VEREADOR JOSE SENA - ESPERANÇA</option>
<option value="81">UAPS VEREADOR MANOEL DOS SANTOS SILVA - LIBERDADE</option>
<option value="10">UAPS VEREADOR MANOEL DOS SANTOS SILVA - PROGRESSO</option>
`;